version: '3.7'
services:
  jenkins:
    image: bobcrutchley/jenkins:latest
    volumes:
    - type: volume
      source: jenkins-home
      target: /var/jenkins-home
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    environment:
    - JENKINS_OPTS="prefix=/jenkins"
volumes:
  jenkins-home:
